// // function add (X,y){
// //     console.log(x+y)
// // }
// // let arr = [5,9];
// // add(...arr);

// // function somefunction(param1, param2){
// //     console.log(param1, param2);
// // }
// // somefunction("hi","there!","how are you?");

// // let addtwoNumbers=(x,y)=>(x+y) 
// // // addtwoNumbers(2,5);for()
// // let resultsArr =[];
// // for(let i=0;i<10;i++){
// //     let result = addTwoNumbers(i,2*i);
//     resultsArr.push(result);
// }
// console.log(resultsArr);

// function testAvailability(x){
//     console.log("Available here:", x);
// }
// testAvailability("Hi!");
// console.log("Not available here:", x);


// let x="global";
// function doingStuff(){
//     let x="local";
//     console.log(x);
// }
// doingStuff();
// console.log(x);

// let x="global";
// function doingStuff(x){
//     console.log(x);
// }
// doingStuff("param");

// Immediately invoked function expression
// (function (){
//     console.log("IIFE")
// })();

// (()=>{
//     console.log("run right away");
// })();

// Recursive functions
// function getRecursive(nr){
//     console.log(nr);
//     getRecursive(--nr);
// }
// getRecursive(3);

// function logRecursive(nr){
//     console.log("Started function:",nr);
//     if(nr>0){
//         logRecursive(nr-1);
//     } else {
//         console.log("done with recursion");
//     }
//     console.log("Ended function:",nr);
// }
// logRecursive(3);
console.log(66);

